default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zbtn-admin_development

test:
  <<: *default
  database: zbtn-admin_test

production:
  <<: *default
  database: zbtn-admin_production
  username: zbtn-admin
  password: <%= ENV['ZBTN-ADMIN_DATABASE_PASSWORD'] %>
