# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1ae4b90e6c146b6ef3a5345b4e3859cb5db96f22db4b79a39790b15c887e0f51d55708572311c90c0132f4b1e6a1aef3c75c914b64c7ae09acff389fe6f67d1

test:
  secret_key_base: fdbb9d1f937a5e9846ccfcc85af1b9ce243580b99249a106649f839b8a408dfbdd6dbcdd766557d2f4fcc8f797a2b25c9475b2c934deb850c5ea4467299a1bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
